### ISSUE TITLE
Generating Random Samples

### ISSUE THREAD

**Issue by PatrykNjoroge** [africanmathsinitiative/Instat#2893] opened 2017-04-04 12:11 UTC
![generating random samples](https://cloud.githubusercontent.com/assets/23484030/24655850/95c78cda-1948-11e7-96c9-bd6ce2d4ed74.PNG)
Hi team, 
I was generating Random samples and I encountered this error while trying to run a command. 
Thanks
Patrick

**Comment by dannyparsons** [comment] 2017-04-04 12:23
Hi Patrick, thanks for reporting this and giving the error message. 
Could you help us my telling us how we can reproduce this error? So could you say which data set you used and the sequence of things you did to leading up to this dialog (if any) and also what you did in the dialog before clicking OK. Thanks.

**Comment by PatrykNjoroge** [comment] 2017-04-04 12:38
Hi Danny, 

Hi @dannyparsons I had two sets of data frames "attitude and air quality" from the stats package. I wanted to perform a simulation of "air quality" data and therefore I was prompted to select the data frame I want to work with. It is important to note that I had previously selected "attitude" before reverting to "air quality". The issue was later resolved by the "reset button". 
Thanks

**Comment by dannyparsons** [comment] 2017-04-04 12:47
Thanks Patrick. 
@africanmathsinitiative/developers Can someone try to reproduce this from Patrick's description? Then try to find the issue if you can reproduce it. If not, then discuss with Patrick to get more details about what he was trying.

**Comment by Lunalo** [comment] 2017-04-04 13:33
@dannyparsons 

Currently , the sample size is being updated in the control but not in r code every time we change the dataframe. 

This dialog has similarity with model dialogs since they are both using ucrDistributions. 

 The dialog also has the old code and to update it needs ucrDistributions to be updated too.

Should we just fix this bug in the old code or wait until ucrDistributions is fixed?

Thanks

**Comment by dannyparsons** [comment] 2017-04-04 13:35
I think it should be fixed now so that it doesn't give an error. Then we can come back to it to re implement it in the new system.

**Comment by Lunalo** [comment] 2017-04-04 13:37
okay, let me fix it.

**Closed** 2017-04-07 15:33 UTC
Labels: bug
