### ISSUE TITLE
File > Open from Library, adding Help

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/Instat#1934] opened 2016-10-23 07:55 UTC
When the option (radio button) is set to its default, it is to open datasets from any of the R packages.  Now from R itself I can type ?diamonds, or help("diamonds") and it will provide more detailed information from the ggplot2 guide, on the data set.  That's great.

So could there be a second Help button in the File > Open from Library dialogue.  It can be just under the list of files, and on the right of the dialogue.  It is disabled until a data set is chosen.  Then, just as Ok is enabled, an alternative is the click on this help, which is enabled at the same time.  If you click on that help button, then you get the help from the documentation, on that data file.  This will presumably be in a browser.  The dialogue remains open.

In the slightly longer term this could also be a great help feature in the Help part of R-Instat.  It would be "Help on R-commands".  I presume it would open a dialogue, but it could simply permit the user to type the name of the command?  That's for later!

I am suggesting Maxwell could look briefly at this, but it could equally be Steven or John.

Roger

**Comment by maxwellfundi** [comment] 2016-10-25 12:44
Currently having a look at this.

Thanks

**Comment by maxwellfundi** [comment] 2016-10-26 06:43
@dannyparsons  i have two ways of doing this and i would like to get your views on this. 
1. We can open the browser on click event of the help button then pass in url for the file we want to open, but the problem is getting the actual url for the html help file of the specific dataset. I have  tried this but seems to work with the index file of the entire library. The specific help files are not opening at all. 
2. We could send the options(help_type = "html") to R then run the ? with the selected dataset which would now open in the browser when we click help. 

I am not sure which we want here.

**Comment by dannyparsons** [comment] 2016-10-26 08:01
I'm not quite sure what the issue is. If you run `help("diamonds")` in R-Instat it will open the help page in your browser. In case the user has changed their default settings then `help(diamonds, help_type = "html")` ensures that it does do to browser and not text file or something. I don't see there being any other option to consider?

**Comment by dannyparsons** [comment] 2016-10-26 09:49
Related this, we could use the commands such as `vignette("introduction", "dplyr")` to display package vignettes in a similar way. I wouldn't suggest it for this dialog but if we eventually had a section on our R packages somewhere, it's worth linking to or possibly for a help section on "moving to R" for example.

**Comment by maxwellfundi** [comment] 2016-10-26 13:07
@dannyparsons  now this has been completed. it can be closed

**Closed** 2016-10-26 13:07 UTC
Labels: enhancement
